### ISSUE TITLE
Build Failure, missing dependency soot

### ISSUE THREAD

**Issue by heutelbeck** [lsds/SEEP#32]
Hello, SEEP Team.

I tried to build you project. I am running into the problem, that the following dependency was not available via the default public Maven repositories. Is there a repository declaration missing, or is it necessary to manually install the dependency into the local repository?

``` XML
    <dependency>
        <groupId>soot</groupId>
        <artifactId>soot-framework</artifactId>
        <version>2.5.0</version>
    </dependency>
```

Thank you very much.

**Comment by pgaref** [comment]
Hello there,

Thanks for the comment. It seems the specific SOOT version is not supported by maven anymore.
You have to manually install it by running the maven-install command below **inside** the SEEP directory:
- mvn install:install-file -Dfile=./libs/soot/soot-framework/2.5.0/soot-2.5.0.jar -DpomFile=./libs/soot/soot-framework/2.5.0/soot-framework-2.5.0.pom 

Then compile the project as described in the home page.

Cheers,
Panagiotis

**Comment by heutelbeck** [comment]
Thank you. The build worked now as documented.
